name: koboldcpp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cxx-compiler
  - gxx=10
  - pip
  - git
  - clblast
  - ninja
  - make
  - packaging
  - pyinstaller
  - libcblas
  - ocl-icd-system
  - libvulkan-loader
  - tk
  - fontconfig
  - freetype
  - psutil
  - jinja2
  - pip:
    - customtkinter
